### ISSUE TITLE
TCP::@txn_id overflow error

### ISSUE THREAD

**Issue by asta331** [scttnlsn/modbus.cr#1]
Hello. Thanks for awesome shard.
I'm using modbus tcp client for fetching data constantly.

When @txn_id reaches UInt16.MAX, it raises overflow error.
I think,
```
    private def next_txn_id
      @txn_id = (@txn_id + 1) & 0xFFFF
    end
```
in + operator raises the error before & operator executed.

I'm using my own fix with the rescue code, but maybe there is a better solution I think.
Thanks!

**Comment by scttnlsn** [comment]
@asta331 Hey, thanks for pointing this out!

I committed a fix here: https://github.com/scttnlsn/modbus.cr/commit/9cd36e453c282ac83582f21525d8af60527c55b2

Instead of catching the exception I just added this conditional:

```crystal
    private def next_txn_id
      if @txn_id == UInt16::MAX
        @txn_id = 0
      else
        @txn_id += 1
      end
    end
```
